name: C/C++ and Bazel CI

on: [push, pull_request]

jobs:
  cpp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    #- name: Checkout submodules
    #  uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Checkout submdoules
      run: git submodule init && git submodule update
    - name: install deps
      run: sudo apt-get update && sudo apt-get install libsdl1.2-dev libsdl-gfx1.2-dev libgmp3-dev autoconf automake libgl1-mesa-dev libglu1-mesa-dev
    - name: install glict
      run: cd vendor/github.com/ivucica/glict/glict && ./autogen.sh && ./configure && make && sudo make install
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    #- name: make distcheck
    #  run: make distcheck

  bazel:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
    # the rest of the steps
    - uses: actions/checkout@v1

    # Caches and restores the bazel build directory.
    - name: Cache bazel build results
      uses: actions/cache@v2.0.0
      env:
        cache-name: bazel-cache
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-master

    - name: Checkout submodules
      run: git submodule init && git submodule update
    - name: install deps
      run: sudo apt-get update && sudo apt-get install autoconf automake libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxext-dev libxrandr-dev libxrender-dev libasound-dev libalsaplayer-dev 
    - name: bazel build
      run: bazel build //:yatc
